name: Test Pull Requests

on:
  workflow_dispatch: # Allow running the workflow manually from the GitHub UI
  pull_request:
    branches:
      - '*'

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Run Tests
        run: dotnet test --configuration Release Hls2TlgrUploader.Tests/Hls2TlgrUploader.Tests.csproj
