name: PR Validation

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: Validate PR
    uses: ./.github/workflows/reusable-tests.yml
    with:
      run-integration: true
    secrets: inherit
